import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-inter",
});


export const metadata = {
  title: "Knotral-Training",
  description: "Generated by create next app",
    icons: {
    icon: "/knotralicon.jpeg", // ✅ custom favicon path
  },
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" className={inter.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
